### ISSUE TITLE
Focus disabled items in dropdown

### ISSUE THREAD

**Issue by hippee-lee** [clr-team/planning#40] opened 2019-07-24 16:27 UTC
## Description of work

_Description of the work to be done, in a clear but succinct manner._
Partially documntation and expand the drop down documentation with current design and design guidelines

## Issue(s)

n/a

## Reviewers

n/a

## Definition of done
* [ ] Reviewed by peers
* [ ] Design sign off (if necessary)

**Comment by colinreedmiller** [comment] 2019-07-24 21:28
Decision process:

0. Problem statement: disabled menu item was not focusable before. In order to make 
it focusable we need design for ‘disabled and focused’ state.

1. Key inital point involves the difference between aria-activedescendant
and Roving Tab Index.

Using aria-activedescendant is the current method and initial estimate is that changing
to Roving Tab Index is out of scope re: development effort required.

2. Thus: initial design solution explores methods of addressing a11y disabled tab 
requirements while retaining our current (aria-activedescendant) method.

3. Design solution pursuant to these limitations:
• Hover / select and focus must all have compliant contrast against its BG
• This is because the focus ring requirement is that it be contrast compliant.
• Disabled item may be non compliant text over BG but focus ring must be compliant.

note: current disabled method is to dim the entire cell to 40%
Preference is given for retaining this method for clarity and simplicity.

Proposed: add left side vertical bar as used elsewhere in Clarity - this will be the focus indicator in dropdowns

For this to be contrast compliant the following changes need to occur:
• Change action blue to shade 5% darker (see left).
• Use black for focus indicator for disabled items  
• All other color callouts remain as they are
• Dimming of disabled item changes from 40% to 60%

By making these changes we select the following as the best options available:

1 . Not changing the aria-activedescendant method of managing focus
2. Not changing the dim method of indicating disabled
3. Not changing the ghlobal slect and hover colors
4. Changing the action color - slightly darker
5. Changing the dimmed percentage for disabled
6. Adding a left side bar as the child focus indicator withing the focused composite

see here:

https://www.w3.org/TR/wai-aria-practices-1.1/#kbd_general_within

**Comment by colinreedmiller** [comment] 2019-07-25 15:25
Second check of contrast requirements specific to this issue suggest that action-blue may not need to be changed. Next step with this is to investigate complex (nested / responsive) cases to validate design approach.

Requires assessment of impact on product.

**Comment by jeeyun** [comment] 2019-08-07 16:43
Closing, as it's a duplicate of #35

**Closed by jeeyun** 2019-08-07 16:43 UTC
Labels: High
